development:
  adapter: postgresql
  encoding: unicode
  database: predictions_development
  host: localhost
  pool: 5
  username: predictions
  password: password
test: &test
  adapter: postgresql
  encoding: unicode
  database: predictions_test
  host: localhost
  pool: 5
  username: predictions
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: predictions_production
  host: localhost
  pool: 5
  username: predictions
  password: password
cucumber:
  <<: *test